1.1 I have a unix script which is calling a python script.
I am getting permission denied for a particular file date_time.yaml which is used as a temporary data
placeholder.

how to debug this issue?

How to check the user which is trying to access the file?

i checked in file system, owner is srv_s025010 and group neo4jadm
owner has R, W, X access
Group has R, X access 

